repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v4.0.1
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: git://github.com/antonbabenko/pre-commit-terraform.git
    sha: v1.52.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.16
    hooks:
      - id: shellcheck
